[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2.7

[hardware]
server ansible_host=127.0.0.1 ansible_port=2222 ansible_user=root ansible_python_interpreter=/usr/bin/python2.7
wifiap ansible_host=192.168.0.1 ansible_port=22 ansible_user=root ansible_python_interpreter=/usr/bin/python2.7
smartos ansible_host=10.100.12.64 ansible_port=22 ansible_user=root ansible_python_interpreter=/opt/local/bin/python
gentoo ansible_host=172.16.25.120 ansible_port=22 ansible_user=root ansible_python_interpreter=/usr/bin/python
