#TODO: hosts - {{ item }} with {{ internal_domain }} is not idempotent
---
- hosts: all
  become: true
  become_user: root
  become_method: sudo

- include: playbook-cron.yml
- include: playbook-hosts.yml
- include: playbook-iptables.yml
- include: playbook-ntp.yml
- include: playbook-resolve.yml
- include: playbook-sshd.yml
- include: playbook-sysctl.yml
- include: playbook-tools.yml
- include: playbook-users.yml
- include: playbook-webserver.yml
