---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    web_server: apache2

  tasks:
    - name: install {{ web_server }}
      package: name={{ web_server }}

    - name: enable sites for {{ web_server }}
      template: src=templates/etc/{{ web_server }}/sites-available/{{ item }}
                dest=/etc/{{ web_server }}/sites-available/{{ item }}
      with_first_found:
        - files:
            - mail.example.org.conf
          skip: true
