---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    user_items:
     - login: user1
       group: user1
       uid: 2001
       git: 2001
       shell: sh
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...oij2==  user1@example.org"
     - login: user2
       group: user2
       uid: 2002
       git: 2002
       shell: bash
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...adv0==  user2@example.org"
     - login: user3
       group: user3
       uid: 2003
       git: 2003
       shell: bash
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...asj5==  user3@example.org"
     - login: user4
       group: user4
       uid: 2004
       gid: 2004
       shell: bash
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...102n==  user4@example.org"

  tasks:
    - name: add groups
      group: name={{ item.group }} gid={{ item.gid }} state=present

    - name: add user
      user: name={{ item.login }} group={{ item.group }} shell={{ item.shell }} uid={{ item.uuid }} groups=root createhome=yes append=yes
      with_items: "{{ user_items }}"

    - name: add ssh-keys to user
      authorized_key: user={{ item.login }} key={{ item.ssh_key }}
      with_items: "{{ user_items }}"

    - name: add ssh-keys to user root
      authorized_key: user=root key="{{ item.ssh_key }}" state=present
      with_items: "{{ user_items }}"
