---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes

  tasks:
   - name: generate dynamic hosts from inventory
     lineinfile:
       state: present
       dest: /etc/hosts
       regexp: '.*{{ item }}$'
       line: "{{ hostvars[item].ansible_host }} {{item}}"
     when: hostvars[item].ansible_host is defined
     with_items: groups['all']
