---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  pre_tasks: []

  tasks:
  - name: gather facts with silent action
    action: setup

  - name: debug facts to stdout
    debug:
     var: hostvars[inventory_hostname]
