---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    user_items:
     - login: user1
       group: user1
       uid: 2001
       gid: 2001
       shell: bash
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...oij2==  user1@example.org"
     - login: user2
       group: user2
       uid: 2002
       gid: 2002
       shell: bash
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...adv0==  user2@example.org"

  tasks:
    - name: add groups
      group: name={{ item.group }} gid={{ item.gid }} state=present

    - name: add user
      user: name={{ item.login }} group={{ item.group }} shell={{ item.shell }} uid={{ item.uuid }} createhome=yes
      with_items: "{{ user_items }}"

    - name: add ssh-keys to user
      authorized_key: user={{ item.login }} key={{ item.ssh_key }}
      with_items: "{{ user_items }}"

    - name: add ssh-keys to user root
      authorized_key: user=root key="{{ item.ssh_key }}" state=present
      with_items: "{{ user_items }}"

    - name: let 'supergroup' group to have passwordless sudo
      lineinfile:  dest=/etc/sudoers state=present regexp='^%supergroup' line='%supergroup ALL=(ALL) NOPASSWD: ALL'

    - name: add sudoers users to supergroup
      user: name={{ item.login }} groups=supergroup append=yes
