---
- include: playbook-iptables.yml

- hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: create nat rule for squid
      iptables:
        table: nat
        chain: PREROUTING
        in_interface: eth0
        protocol: tcp
        match: tcp
        destination_port: 80
        jump: REDIRECT
        to_ports: 3128
        comment: rule for redirect to squid
        become: yes
