---
- hosts: log-collector
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: create log directories on remote server - main
      file: state=directory path=/var/log/remote/{{ item }}
      with_items:
        - "{{ groups['web_servers'] }}"

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: install atop if absent
      yum: name={{ item }} state=present
      with_items:
        - atop
        - mcelog
      when: ansible_distribution == 'CentOS'
      notify: start {{ item }}

    - name: install atop if absent
      apt: name={{ item }} state=present
      with_items:
        - atop
        - mcelog
      when: ansible_distribution == 'Ubuntu'



  handlers:
    - name: start atop
      service: enabled=true name=atop state=started

    - name: start mcelog
      service: enabled=true name=mcelog state=started
