- hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: install linux package apt or rpm
      package: name={{ item }} state=present
      with_items:
        - rkhunter
        - lynis
        - atop
        - mcelog
        - lm_sensors
