---
- hosts: all
  tasks:
    - name: do not allow root login via ssh
      lineinfile: backrefs=yes dest=/etc/ssh/sshd_config regexp="^PermitRootLogin yes"line="PermitRootLogin no"
      notify: reload sshd

    - name: do not allow password auth via ssh
      lineinfile: backrefs=yes dest=/etc/ssh/sshd_config regexp="#PasswordAuthentication yes" line="PasswordAuthentication no"
      notify: reload sshd

    - name: do not allow use pam via ssh
      lineinfile: backrefs=yes dest=/etc/ssh/sshd_config regexp="^UsePAM yes" line="UsePAM no"
      notify: reload sshd

    - name: restrict listening interface
      lineinfile: dest=/etc/ssh/sshd_config regexp="^ListenAddress {{ hostvars[host].ansible_default_ipv4.address }}" state=present
      notify: reload sshd

  handlers:
    - name: reload sshd
      service: name=sshd state=restarted enabled=true
