#TODO: centos/rhel/ubuntu/debian work
#TODO: ipv6tables
#TODO: ssh-keys
#TODO: hosts - {{ item }} with {{ internal_domain }} is not idempotent
---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

- include: playbook-cron.yml
- include: playbook-hostname.yml
- include: playbook-hosts-dynamic.yml
- include: playbook-hosts-static.yml
- include: playbook-iptables.yml
- include: playbook-mc.yml
- include: playbook-ntp.yml
- include: playbook-resolve.yml
- include: playbook-sshd.yml
- include: playbook-sysctl.yml
- include: playbook-users.yml

- include: playbook-rpm.yml
  when: ansible_distribution == 'CentOS' or 'Red Hat Enterprise Linux'

- include: playbook-apt.yml
  when: ansible_distribution == 'Ubuntu' or 'Debian'
