- hosts: all
  become: true
  become_user: root
  become_method: sudo


  pre_tasks:
   - name: install epel repository
     yum_repository:
       name: epel
       description: EPEL YUM repo
       baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  tasks:
    - name: install rpm
      yum: name={{ item }} state=present
      with_items:
        - rkhunter
        - lynis
     when: packages is defined and ansible_distribution == 'CentOS'
