---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: install git package
      apt: name=git state=present
      when: ansible_distribution == "Ubuntu"

    - name: install git package
      yum: name=git state=present
      when: ansible_distribution == "CentOS"

    - name: clone ansible repository to server
      git:
        repo: 'git://github.com/ansible/ansible.git'
        dest: '/opt/ansible'
        update: yes

