---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    web_server: apache

  tasks:
    - name: install {{ web_server }}
      apt: name=apache2
      when: "ansible_distribution == 'Ubuntu' and web_server == 'apache'"

    - name: install {{ web_server }}
      yum: name=httpd
      when: "ansible_distribution == 'CentOS' and web_server == 'apache'"

    - name: install {{ web_server }}
      package: name=nginx state=present
      when: web_server == 'nginx'

    - name: enable sites for {{ web-server }}
      template: src=templates/etc/{{ web-server }}/sites-available/{{ item }}
                dest=/etc/{{ web-server }}/sites-available/{{ item }}
      with_items:
         - mail.example.org.conf
         - jabber.example.org.conf
      notify: reload {{ web-server }}

  handlers:
    - name: reload {{ web-server }}
      service: enabled=true name={{ web-server }} state=restarted
