---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
   - vars.yml

  tasks:
    - name: set sysctl settings
      sysctl:
        name="{{ item.key }}" value="{{ item.value }}"
        sysctl_set=yes state=present reload=yes
      with_dict: "{{
                    (sysctl_set_filesystem) | combine
                    (sysctl_set_netcore) | combine
                    (sysctl_set_kernel) | combine
                    (sysctl_set_ipv4)
                  }}"
