---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    internal_domain: example.org
  tasks:
   - name: generate dynamic hosts from inventory
     lineinfile:
       state: present
       dest: /etc/hosts regexp='.*{{ item }}$'
       line: "{{ hostvars[item].ansible_host }} {{item}}"
     when: hostvars[item].ansible_default_ipv4.address is defined
     with_items: groups['all']
