---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: disable firewalld for running iptables
      service: name=firewalld enabled=false state=stopped
      when: ansible_distribution == 'CentOS'

    - name: check if iptables-services are installed
      yum: name=iptables-services state=present
      when: ansible_distribution == 'CentOS'

    - name: disable ufw for running iptables
      service: name=ufw enabled=false state=stopped
      when: ansible_distribution == 'Ubuntu'

    - name: check if iptables-services are installed
      apt: name=iptables-persistent state=present
      when: ansible_distribution == 'Ubuntu'

    - name: accept already established flows
      iptables: chain=INPUT ctstate=ESTABLISHED,RELATED comment="active flows" jump=ACCEPT

    - name: accept new http flows for web-server
      iptables: chain=INPUT protocol=tcp match=tcp destination_port=80 comment="http access" jump=ACCEPT

    - name: accept new ssh flows for remotely-managed server
      iptables: chain=INPUT protocol=tcp match=tcp destination_port=22 comment="ssh access" jump=ACCEPT

    - name: block all other flows for protection - global policy to chain
      iptables: chain=INPUT jump=DROP
