---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
   - vars.yml

  tasks:
    - name: set sysctl settings
      sysctl: sysctl_set=yes reload=yes state=present
        name="{{ item.key }}"
        value="{{ item.value }}"
      with_dict: "{{ sysctl_settings }}"
