---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    internal_domain: example.org
  tasks:
   - name: setting hostname from inventory
     hostname: name="{{ inventory_hostname }}.{{ internal_domain }}"
