---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: do not allow root login via ssh
      lineinfile: backrefs=yes state=present dest=/etc/ssh/sshd_config regexp="^PermitRootLogin yes" line="PermitRootLogin no"
      notify: reload sshd

    - name: do not allow password auth via ssh
      lineinfile: backrefs=yes state=present dest=/etc/ssh/sshd_config regexp="#PasswordAuthentication yes" line="PasswordAuthentication no"
      notify: reload sshd

    - name: do not allow use pam via ssh
      lineinfile: backrefs=yes state=present dest=/etc/ssh/sshd_config regexp="^UsePAM yes" line="UsePAM no"
      notify: reload sshd
      when: ansible_default_ipv4.address != "127.0.0.1"

    - name: restrict listening interface
      lineinfile:
              state=present
              dest=/etc/ssh/sshd_config
              regexp="^ListenAddress {{ ansible_default_ipv4.address }}"
              line="ListenAddress {{ ansible_default_ipv4.address }}"
      when: ansible_default_ipv4.address != "127.0.0.1"
      notify: reload sshd

  handlers:
    - name: reload sshd
      service: name=sshd state=restarted enabled=true
