---
- hosts: all
  become: true
  become_user: root
  become_method: sudo

  vars:
    internal_domain: example.org

  tasks:
   - name: setting hostname from inventory
     hostname: name="{{ inventory_hostname }}.{{ internal_domain }}"
     when: internal_domain is defined

   - name: setting hostname from inventory
     hostname: name="{{ inventory_hostname }}"
     when: internal_domain is not defined
