---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    gitlab_host: "192.168.0.200"
    gitlab_admin_username: "username"
    gitlab_admin_password: "password"

    gitlab_new_users:
     - name: "Developer One"
       user: developer1
       pass: changeme
       mail: developer1@example.org
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...oij2==  user1@example.org"
     - name: "Developer Two"
       user: developer2
       pass: changeme
       email: developer2@example.org
       ssh_key: "ssh-rsa AAAAB3NzaC1yc....snip...adv0==  user2@example.org"

  tasks:

    - name: install or check epel-release
      yum: name=epel-release state=present

    - name: install or check pip
      yum: name=python-pip state=present

    - name: install or check pyapi-gitlab
      pip: name=pyapi-gitlab

    - name: add gitlab user
      delegate_to: "{{ gitlab_host }}"
      action: gitlab_user
                    server_url="http://{{ gitlab_host }}"
                    validate_certs=true
                    login_user="{{ gitlab_admin_username }}"
                    login_password="{{ gitlab_admin_password }}"
                    name="{{ item.name }}"
                    username="{{ item.user }}"
                    password="{{ item.pass }}"
                    email="{{ item.email }}"
                    sshkey_name=default
                    sshkey_file="{{ item.ssh_key }}"
                    state=present
      with_items: "{{ gitlab_new_users }}"
