- hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: install apt
      apt: name={{ item }}
      with_items:
        - rkhunter
        - lynis
        - atop
        - mcelog
        - lm_sensors
     when: packages is defined and ansible_distribution == 'Ubuntu'
